---
title: "Homework 0"
author: "Alihan Zer"
date: "29 10 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ARIMA

  In ARIMA method, the data should be stationary. In other words, the properties of the series do not depend on the time when it is captured. Additionally, ARIMA can work only on a single variable. 

  This example is important because it introduces the forecasting methodology using ARIMA models in R. The steps are loading R packages, examining the data, decomposing the data, stationarity, autocorrelation and choosing model order, fitting an ARIMA model, and evaluating and iterating. 

## Exponential Smoothing

  Exponential smoothing is a univariate method for time series and forecasting. There are many ways to do exponential smoothing and this situation makes exponential smoothing flexible. 
  
  Exponential smoothing forecasting methods are similar in that a prediction is a weighted sum of past observations, but the model explicitly uses an exponentially decreasing weight for past observations. One of the most popular forecasting methods, Holt – Winters method is an application of exponential smoothing.

## GARCH Method

  GARCH stands for generalized autoregressive conditional heteroskedasticity. GARCH is a statistical model used in analyzing time-series data where the variance error is believed to be serially autocorrelated. Heteroskedasticity describes the irregular pattern of variation of an error term. GARCH process is an approach to estimating the volatility of financial markets.
  
## Vector Autoregression

  Vector Autorregression (VAR) is a flexible and easy to use model. This model is useful especially for describing the dynamic behavior of economic and financial time series, and for forecasting. One of the most important features of this model is it multivariate and it is superior to univariate models. 
  
## TBATS

  This method is a combination of several methods. It stands for “Trigonometric terms for seasonality, Box-Cox transformations for heterogeneity, ARMA errors for short-term dynamics, Trend, Seasonal”. Compared to other methods, its mean absolute percentage error is low, which means it is better than most of the methods.
